Import version 1.0.4-cl5.1.0u11 from Cumulus Linux

diff --git a/debian/libnss-tacplus.prerm b/debian/libnss-tacplus.prerm
--- a/debian/libnss-tacplus.prerm
+++ b/debian/libnss-tacplus.prerm
@@ -7,6 +7,8 @@ if [ "$1" = remove ]; then
     if [ -e "/etc/nsswitch.conf" ]; then
         sed -i -e '/^passwd:.*tacplus\s/s/tacplus\s//' \
             /etc/nsswitch.conf || true # don't prevent remove on error
+        sed -i -e '/^group:.*tacplus\s/s/tacplus\s//' \
+            /etc/nsswitch.conf || true # don't prevent remove on error
     fi
 fi
 
